on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Create Release
        run: |
          npm install -g pkg

          npm install
          npm run build
          npm run release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.2
          release_name: Release 1.2
          draft: false
          prerelease: false
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./devserver-win.exe
          asset_name: devserver-win.exe
          asset_content_type: application/vnd.microsoft.portable-executable
    