on:
  push:
    tags:
      - '*'

name: Create Release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Building Package
        run: |
          npm install -g pkg

          npm install
          npm run build
          npm run release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Download your OS specific binary from below
          files: |
            ./release/linux/liascript-devserver
            ./release/macos/liascript-devserver
            ./release/windows/liascript-devserver.exe
